name: flutter_smart_timer
description: A smart timer designed for easy use, featuring interval functions and customizable duration settings.
version: 1.0.9
homepage: https://github.com/Anykeykin/smart_timer

environment:
  sdk: ^3.1.5

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
