name: flutter_smart_timer
description: Timer for best setup and use
version: 1.0.7
homepage: https://github.com/Anykeykin/smart_timer

environment:
  sdk: ^3.1.5

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
